#! /usr/bin/python3
# -*- python -*-

###############################################################################
# Copyright 2014 Emil Karlén.
# 
# This file is part of file-name-resolver.
# 
# Wilde is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# Wilde is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with Wilde.  If not, see <http://www.gnu.org/licenses/>.
###############################################################################


###############################################################################
# - parse arguments -
###############################################################################


import sys
import argparse

EXIT_USAGE = 2
EXIT_INVALID_ARGUMENTS = 3

# Returns an open file.
def parse_command_line():
    parser = argparse.ArgumentParser()
    parser.add_argument("file",
                        metavar="FILE",
                        help="A file that contains the resolve specification.")
    args = parser.parse_args()
    try:
        return open(args.file,mode='r')
    except OSError:
        sys.exit(EXIT_INVALID_ARGUMENTS)


###############################################################################
# - main -
###############################################################################


file = parse_command_line()
print("testdata/existing-file.txt")
